### ISSUE TITLE
NetworkManager 1.36.0 fails to get IP configuration

### ISSUE THREAD

**Issue by siavashs** [ohwgiles/NetworkManager-f5vpn#12]
I've been running the master branch of the plugin on ArchLinux since August 2021.
Today an update to NetworkManager broke the plugin:
```
[2022-02-25T10:03:58+0100] [ALPM] upgraded libnm (1.34.0-1 -> 1.36.0-1)
[2022-02-25T10:04:01+0100] [ALPM] upgraded networkmanager (1.34.0-1 -> 1.36.0-1)
```
The plugin now throws this error:
```
config: no VPN gateway address received
did not receive valid IP config information
```
I'm trying to find out which change in NM broke the plugin but so far this change caught my eye:
>* The handling of Layer 3 configurations has been substantially reworked.
  While this is mostly internal change, it results in more robust
  behavior when addressing information from multiple sources (DHCP,
  manually configured, VPN) need to be applied simultaneously.
  Overall performance and memory use have also slightly improved.

https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/main/NEWS

Let me know if you need more information to resolve the issue.

**Comment by ohwgiles** [comment]
@siavashs excellent report thanks, now solved. I've made a new tag and updated the AUR package too.
