### ISSUE TITLE
Link not starting or establishing with latest networkmanager

### ISSUE THREAD

**Issue by GazzaC** [ohwgiles/NetworkManager-f5vpn#13]
Hi, 

I upgraded to networkmanager-1.36.4-1 and the link does not establish whilst connecting to the VPN.

I re-compiled from the source and got same result with this version of networkmanager. I downgraded to networkmanager-1.34.0-1 package and network connection works.

Happy to provide any debugs etc.

**Comment by ohwgiles** [comment]
Works for me with `networkmanager-1.36.4-1`. If you are using the AUR package, make sure to force a rebuild, kill any running instances and restart network manager.

**Comment by GazzaC** [comment]
My bad, I was using an earlier package 0.4-1

Thanks
