### ISSUE TITLE
Does it support sms OTP?

### ISSUE THREAD

**Issue by alperenkose** [ohwgiles/NetworkManager-f5vpn#6]
Hi,

After entering username and password on popup, it fails with the following output on syslog. It should have asked for a one time password instead, does the plugin support it? 

`final secrets request failed to provide sufficient secrets`

Thanks,

**Comment by ohwgiles** [comment]
It depends on the method the server uses to request the OTP. Essentially, the popup tries to replace the web form flow by parsing the HTML returned from the login page. This will only work if it has not been too customized. The plugin has been tested to work with such simple pages which request an OTP in the same form as the username/password request (see [this code](https://github.com/ohwgiles/NetworkManager-f5vpn/blob/75d6d989a3c452444136fd272e64d9d84d876fcd/lib/f5vpn_auth.c#L493) which looks for `<input>` tags).

This clearly isn't good enough for all servers. As suggested in #5, another way to support this would be having a "use web login" mode, which delegates the authentication to the browser, and installs a .desktop handler to complete the flow when the authentication in the browser finishes.

**Comment by ohwgiles** [comment]
NB: Web login implemented in da79b3f170cb
