### ISSUE TITLE
NetworkManager can't find libnm-vpn-plugin-f5vpn.so on Ubuntu 20.04 64 bits

### ISSUE THREAD

**Issue by DanielVallejos** [ohwgiles/NetworkManager-f5vpn#8]
Hello 

I follow the compilation and install commands:

	cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
	make
	sudo make install

Done without errors.

But when I go to nm-applet the following error appear:

user@machine:/usr/local/lib$ nm-applet 
** Message: 03:44:12.785: vpn: (f5vpn,/usr/lib/NetworkManager/VPN/nm-f5vpn-service.name) file "libnm-vpn-plugin-f5vpn.so" not found. Did you install the client package?

The work around is as root:

ln -s /usr/lib/NetworkManager/libnm-vpn-plugin-f5vpn.so /usr/lib/x86_64-linux-gnu/NetworkManager

and problem done.

As you can see, the cmake installer put the .so file in /usr/lib/NetworkManager instead of /usr/lib/x86_64-linux-gnu/NetworkManager

Thanks!

**Comment by ohwgiles** [comment]
@DanielVallejos please try with the latest master
